In [1]:
import numpy as np

In [29]:
np.arange(5,21,3)

array([ 5,  8, 11, 14, 17, 20])

In [27]:
np.linspace(5,21,3)

array([ 5., 13., 21.])

In [30]:
np.linspace(5,21,4,endpoint=False)

array([ 5.,  9., 13., 17.])

In [44]:
a = np.array([1, 2, 4, 3, 5, 4, 8, 2, 1])

In [51]:
b = a.reshape(3,3)

In [52]:
b.shape

(3, 3)

In [54]:
b[1]

array([3, 5, 4])

In [55]:
"Hello"[0]

'H'

In [62]:
values = [[3, 4, 5, 1], [33, 6, 1, 2]] 
v = values[0][0] 
for lst in values: 
    print(lst)
    for element in lst: 
        if v > element: 
            v = element 
            print(v)

[3, 4, 5, 1]
1
[33, 6, 1, 2]
